config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/about'
  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
validates :title, presence: true
validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
validates :comment, presence: true
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
    user_path(resource)
end

protected
def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
	devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	def create
	  @book = Book.find(params[:book_id])
	  @comment = @book.book_comments.new(book_comment_params)
	  @comment.user_id = current_user.id
	  @comment.save
	  redirect_to book_path(@book)
	end

	def destroy
  	  comment = BookComment.find(params[:id])
  	  comment.destroy
      redirect_to book_path(params[:book_id])
	end

	 private
	 def book_comment_params
	   params.require(:book_comment).permit(:comment)
	 end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @booknew = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id),notice: 'Book was successfully created.'
    else
      @user = current_user
      @books = Book.all
      render :index
      flash[:notice] = 'error'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
    redirect_to books_path
    end
  end

def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id),notice: 'Book was successfully updated.'
    else
      render :edit
      flash[:notice] = 'error'
    end
  end

def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
  	book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end


  def destroy
  	book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
    redirect_to user_path(current_user)
    end
  end

  def show
  	@user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id),notice: 'User was successfully updated.'
    else
      flash[:notice]="error"
      render :edit


    end
  end

private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newbook.html.erb
<h1>New book</h1>
<!-- form_for部分 -->
        <%= form_for(book) do |f| %>
        <% if book.errors.any? %>
        <%= book.errors.count %>error
        <% book.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
        <% end %>

　　　　<div class="row">
        <%= f.label :title %>
        <%= f.text_field :title, class:"col-xs-12" %>
      </div>

      <div class="row">
          <%= f.label :body %>
          <%= f.text_area :body,class:"col-xs-12" %>
      </div>

      <div class="row">
          <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
      </div>
        <% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class ="col-xs-6 col-xs-offset-3">
	<h1>Editing Book</h1>
	  <%= form_for(@book) do |f| %>
	  	<% if @book.errors.any? %>
	        <%= @book.errors.count %>error
	        <% @book.errors.full_messages.each do |message| %>
	        <%= message %>
	  <% end %>
	<% end %>

	<div class="row">
		<%= f.label :title %>
	 	 <%= f.text_field :title, class:"col-xs-12" %>
	</div>

	<div class="row">
	<%= f.label :body %>
	  <%= f.text_area :body ,class:"col-xs-12" %>
	</div>

	<div class="row">
	 <%= f.submit 'Update Book', class:"col-xs-12 btn btn-primary" %>
	</div>
	<% end %>
	<%= link_to "Show", book_path(@book) %> |
	<%= link_to "Back", books_path %>
	</div>
</div>

app/views/books/index.html.erb
<div class="row">
    <div class="col-xs-3">
      <%= render 'users/userinfo',user:@user %>
      <%= render 'books/newbook', book:@book %>

    </div>

    <div class="col-xs-9">
      <h1>Books</h1>
          <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
             <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",size:'20×20' %>
                <% end %>
              </td>
             <td><%= link_to book.title, book_path(book.id) %></td>
             <td><%= book.body %></td>
             <td>
              <% if book.favorited_by?(current_user) %>
                    <li>
                      <%= link_to book_favorites_path(book), method: :delete do %>
                        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                        <%= book.favorites.count %>
                      <% end %>
                    </li>
                    <% else %>
                    <li>
                      <%= link_to book_favorites_path(book), method: :post do %>
                        <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                        <%= book.favorites.count %>
                      <% end %>
                    </li>
                    <% end %>
             </td>
             <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<div class="row">
    <div class="col-xs-3">
      <%= render 'users/userinfo',user:@user %>
      <%= render 'books/newbook', book:@booknew %>
    </div>

    <div class="col-xs-9">
       <h1>Book detail</h1>
       <table class="table table-hover">
            <tbody>
                <tr>
                 <td><%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg",size:'100×100' %><br>
                    <%= @user.name %>
                    <% end %>
                 </td>

                 <td><%= link_to @book.title, book_path(@book.id) %></td>
                 <td><%= @book.body %></td>

                 <td>
                   <% if @book.favorited_by?(current_user) %>
                    <li>
                      <%= link_to book_favorites_path(@book), method: :delete do %>
                        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                        <%= @book.favorites.count %>
                      <% end %>
                    </li>
                    <% else %>
                    <li>
                      <%= link_to book_favorites_path(@book), method: :post do %>
                        <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                        <%= @book.favorites.count %>
                      <% end %>
                    </li>
                    <% end %>
                 </td>

                 <td><%= @book.book_comments.count %>件コメント</td>
                 <% if @book.user.id == current_user.id %>
                 <td><%= link_to "Edit", edit_book_path(@book),class:"btn btn-success" %></td>
                 <td><%= link_to "Destroy", book_path(@book.id), method: :delete,data: { confirm:"本当に消しますか?"},class:"btn btn-danger" %></td>
                 <% end %>
                </tr>
            </tbody>
        </table>

                  <% @book.book_comments.each do |book_comment| %>
                  <table>
                    <tbody>
                      <tr>
                        <td><%= link_to user_path(@user.id) do %>
                        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg",size:'100×100' %><br>
                        <% end %>
                        </td>
                        <td><%= book_comment.comment %></td>
                      </tr>
                      <td>
                        <% if book_comment.user == current_user %>
                        <%= link_to "Destroy", book_book_comment_path(book_id: @book, id: book_comment), method: :delete,data: { confirm:"本当に消しますか?"},class:"btn btn-danger" %>
                        <% end %>
                      </td>
                    <% end %>
                    </tbody>
                  </table>




                      <%= form_for [@book, @book_comment] do |f| %>
                      <div class="row">
                        <div class="col-sm-12">
                          <%= f.text_area :comment,class:"col-xs-12" %>
                        </div>
                      </div>
                      <%= f.submit "送信する" %>
                    <% end %>
    </div>
</div>

app/views/home/about.html.erb
<h1>Welcome to <span class= "glyphicon glyphicon-book" >
</span><strong>Bookers!</strong></h1>

app/views/home/home.html.erb
<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
          <%= link_to  "Log in", new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1 " %>
      </div>
      <div class="row">
        <%= link_to  "Sign up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1" %>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<head>
	<meta charset="utf-8">
	<title></title>
	<%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav  navbar-right">
          <% if user_signed_in? %>
		<li>
			<%= link_to "Home", user_path(current_user.id),class:"glyphicon glyphicon-home" %>
		</li>
		<li>
			<%= link_to "Users", users_path,class:"glyphicon glyphicon-link" %>
		</li>
		<li>
			<%= link_to "Books", books_path,class:"glyphicon glyphicon-edit" %>
		</li>
		<li>
		 <%= link_to "logout", destroy_user_session_path, method: :delete,class:"glyphicon glyphicon-log-out" %>
		</li>
	<% else %>
		<li>
			<%= link_to "Home", root_path,class:"glyphicon glyphicon-home" %>
		</li>
		<li>
			<%= link_to "About", home_about_path,class:"glyphicon glyphicon-link" %>
		</li>
		<li>
			<%= link_to "sign up", new_user_registration_path,class:"glyphicon glyphicon-edit" %>
		</li>
		<li>
			<%= link_to "Login", new_user_session_path, class:"glyphicon glyphicon-log-out" %>
		</li>
	<% end %>
      </ul>
    </nav>
  </div>
</header>
<div class = "main">
	<div class="container">
		<p><%= notice %></p>
	<%= yield %>
	</div>
</div>

<footer>
  <div class="container">
  	<div class="row">
    	<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

</body>

app/views/users/_userinfo.html.erb
<h1>User info</h1>
        <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>

        <table class="table">
        	<tbody>
        		<tr>
        			<th>name</th>
        			<th><%= user.name %></th>
        		</tr>

        		<tr>
        			<th>introduction</th>
        			<th><%= user.introduction %></th>
        		</tr>
        	</tbody>
        </table>
      <div class="row">
        <%= link_to "" , edit_user_path(user.id),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
      </div>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_for(@user) do |f| %>

<%= f.label :name %>
  <%= f.text_field :name %>
<br>
<%= f.label :profile_image,"Image" %>
<%= f.attachment_field :profile_image %>


 <%= f.label :introduction %>
  <%= f.text_area :introduction %>
<br>
<%= f.submit 'Update User' %>
<%end%>

app/views/users/index.html.erb
<div class="row">
    <div class="col-xs-3">
      <%= render 'users/userinfo',user:@user %>
      <%= render 'books/newbook',book:@book %>

    </div>

    <div class="col-xs-9">
      <h1>Users</h1>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
             <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",size:'20×20' %></td>
             <td><%= user.name %></td>
             <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-xs-3">
      <%= render 'users/userinfo',user:@user %>
      <%= render 'books/newbook', book:@book %>

    </div>

    <div class="col-xs-9">
      <h1>Books</h1>
          <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
             <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",size:'20×20' %>
                <% end %>
              </td>
             <td><%= link_to book.title, book_path(book.id) %></td>
             <td><%= book.body %></td>
             <td>
              <% if book.favorited_by?(current_user) %>
                    <li>
                      <%= link_to book_favorites_path(book), method: :delete do %>
                        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                        <%= book.favorites.count %>
                      <% end %>
                    </li>
                    <% else %>
                    <li>
                      <%= link_to book_favorites_path(book), method: :post do %>
                        <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                        <%= book.favorites.count %>
                      <% end %>
                    </li>
                    <% end %>
             </td>
             <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>